### ISSUE TITLE
Attachment details not returned

### ISSUE THREAD

**Issue by sylnit** [amirsanni/php-ews-wrapper#1]
https://github.com/amirsanni/php-ews-wrapper/blob/53f69fbf9310b8283a5da9a452e84080358975c4/src/Messages/Message.php#L363

There is no properly documented way to retrieve attachments from emails.

The library returns only the name of the attachments without other details. This makes it difficult to retrieve the attachments of an email.

To fix this I modified the referenced line 363 to return the raw attachments as shown below.

**$det->attachments = $msg_info->Attachments && $msg_info->Attachments->FileAttachment ? $msg_info->Attachments->FileAttachment : "";**

Then other parts of the code that need it manipulate the code as needed with the knowledge of the underlying php-ews to retrieve attachments from email and save them.

**Comment by amirsanni** [comment]
Cool. That line returned just the name. Will update. Thanks
