### ISSUE TITLE
Tasks not working

### ISSUE THREAD

**Issue by codeicheck** [amirsanni/php-ews-wrapper#4]
Hi,

looks like there's an issue with tasks. It searches for tasks but tries to return contacts. 

To solve this, the get function in [this ](https://github.com/amirsanni/php-ews-wrapper/blob/master/src/Tasks.php)file should be sth like:

`public function get(int $page_number=1){
        $response = $this->folder->getItems($page_number, DistinguishedFolderIdNameType::TASKS, $this->limit);

        $res = new \stdClass();

        if($response[0]->ResponseClass == ResponseClassType::SUCCESS){
            //format the response by returning specific fields
            $retrieved_tasks = $response[0]->RootFolder->Items->Task;
            $res->tasks = $retrieved_tasks;
            $res->status = 1;
        }

        else{
            $res->msg = $response[0]->ResponseCode.": ".$response[0]->MessageText;
            $res->status = 0;
        }

        return $res;
    }`

instead of

` $response = $this->folder->getItems($page_number, DistinguishedFolderIdNameType::TASKS, $this->limit);

        $res = new \stdClass();

        if($response[0]->ResponseClass == ResponseClassType::SUCCESS){
            //format the response by returning specific fields
            $retrieved_contacts = $response[0]->RootFolder->Items->Contact;

            $res->contacts = $retrieved_contacts;
            $res->status = 1;
        }

        else{
            $res->msg = $response[0]->ResponseCode.": ".$response[0]->MessageText;
            $res->status = 0;
        }

        return $res;`

**Comment by amirsanni** [comment]
Fixed here https://github.com/amirsanni/php-ews-wrapper/pull/6
