### ISSUE TITLE
SOAP client returned status of 401.

### ISSUE THREAD

**Issue by tolgakocadag** [amirsanni/php-ews-wrapper#9]
It was working fine until October, but a new security measure seems to have arrived. What should we do?

[Example : ](https://stackoverflow.com/questions/33594652/exchange-web-services-issue-soap-client-returned-status-of-401-in-php#:~:text=Status%20code%20401%20means%20that,Oauth%20-auth%20scheme%20for%20EWS.)

**Comment by amirsanni** [comment]
This https://github.com/amirsanni/php-ews-wrapper/pull/10 should fix it.

**Comment by tolgakocadag** [comment]
not working :( , How can I get access token?

**Comment by amirsanni** [comment]
https://github.com/jamesiarmes/php-ews/issues/212#issuecomment-1278220343

**Comment by tolgakocadag** [comment]
Thank you very much, I created a token. but I am getting an error like this. $this->ews->authWithOauth2($access_token);

**Comment by tolgakocadag** [comment]
Fatal error: Uncaught Error: Call to undefined method jamesiarmes\PhpEws\Client::authWithOauth2() in /var/www/html/ews/class/vendor/amirsanni/php-ews-wrapper/src/PhpEwsWrapper.php:44 Stack trace: #0 /var/www/html/ews/sendmail.php(165): amirsanni\phpewswrapper\PhpEwsWrapper->__construct() #1 {main} thrown in /var/www/html/ews/class/vendor/amirsanni/php-ews-wrapper/src/PhpEwsWrapper.php on line 44
